accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('/', views.index),
]

basicallytwins/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accounts.views import (login_view, logout_view, register_view, user_settings, user_password)
from core.views import (index, list_one, list_one_new)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('list/realmoney/', list_one, name='list_one'),
    path('list/realmoney/new', list_one_new, name='list_one_new'),

    path('settings/', user_settings, name='settings'),
    path('settings/password/', user_password, name='password'),

    path('oauth/', include('social_django.urls', namespace='social')),  # <--
    
    path('', include('core.urls', namespace='user')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.lander , name='lander'),
    path('products/', views.index, name='home'),
    
    path('catagory/', include([
        path('', views.catagory_list, name='catagory_list'),
        path('<slug:slug>/', views.catagory_detail, name='catagory_detail'),
        ])),
 
	path('ads/<int:id>/', views.advert_redirect, name='advert_redirect'),    

    path('@<str:username>/', include([
        path('', views.user_profile, name='user_profile'),
        path('create_product', views.create_product, name='create_product'),
        path('admin_create_product', views.admin_create_product, name='admin_create_product'),
        path('all_advert', views.all_advert, name='all_advert'),
        path('create_advert', views.create_advert, name='create_advert'),
        path('edit_advert', views.edit_advert, name='edit_advert'),
        ])),
    # path('new', views.card_create, name='card_create'),
    # path('news', views.fetch_news, name='fetch_news'),
	
    path('tags/', include([
		path('', views.all_tags, name='all_tags'),
		path('<slug:slug>/', views.tag_detail, name='tag_detail'),
		])),

    path('product/<slug:slug>/', views.product_detail, name='product_detail'),
    path('product/<slug:slug>/<str:username>/edit', views.edit_product, name='edit_product'),
    path('product/<slug:slug>/<str:username>/delete', views.delete_product, name='delete_product'),
    path('claim_products/', views.claim_list, name='claim_list'),
    path('claim_products/<slug:slug>/', views.claim_product, name='claim_product'),
    path('claim_products/<slug:slug>/@<str:username>/', views.check_claim, name='check_claim'),
    
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout
)

User = get_user_model()

class UserLoginForm(forms.Form):
    username = forms.CharField(label='',widget = forms.TextInput(attrs={'placeholder': 'User Name', 'class':'form-control'}))
    password = forms.CharField(label='',widget = forms.PasswordInput(attrs={'placeholder': 'Password', 'class':'form-control'}))

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError("This user does not exist.")
            if not user.check_password(password):
                raise forms.ValidationError("Incorrect Password.")
            if not user.is_active:
                raise forms.ValidationError("This user is no longer Active.")
        return super(UserLoginForm, self).clean(*args, **kwargs)


class UserRegisterForm(forms.ModelForm):
    username = forms.CharField(label='',widget = forms.TextInput(attrs={'placeholder': 'User Name', 'class':'form-control'}))
    email = forms.EmailField(label='',widget = forms.TextInput(attrs={'placeholder': 'Email Address', 'class':'form-control'}))
    password = forms.CharField(label='',widget=forms.PasswordInput(attrs={'placeholder': 'Password', 'class':'form-control'}))

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password'
        ]

    def clean_email2(self):
        email = self.cleaned_data.get('email')
        email_qs = User.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError("This email has already been registered")
        return email

accounts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.urls import reverse

from django.contrib.auth.forms import AdminPasswordChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages

from social_django.models import UserSocialAuth

from django.contrib.auth import (
	authenticate,
	get_user_model,
	login,
	logout
)
from django.shortcuts import render, redirect, HttpResponseRedirect
from .forms import UserLoginForm, UserRegisterForm

def login_view(request):
	next = ""

	if request.GET:  
		next = request.GET['next']

	dbug = settings.DEBUG
	form = UserLoginForm(request.POST or None)
	if form.is_valid():
		username = form.cleaned_data.get("username")
		password = form.cleaned_data.get("password")
		user = authenticate(username=username, password=password)
		login(request,user)
		if next == "":
			return HttpResponseRedirect(reverse('user:home'))
		else:
			return HttpResponseRedirect(next)

	context = {
		"name_nav" : 'login',
		"nbar" : "login",
		"form" : form,
		"dbug" : dbug,
		'page' : 'full-page',

	}
	return render(request, 'accounts/login.html', context)

def register_view(request):
	next = ""

	if request.GET:
		next = request.GET['next']

	dbug = settings.DEBUG
	form = UserRegisterForm(request.POST or None)
	if form.is_valid():
		user = form.save(commit=False)
		password = form.cleaned_data.get("password")
		user.set_password(password)
		user.save()
		new_user = authenticate(username=user.username, password=password)
		login(request, new_user)
		# change redirect to profile page
		if next == "":
			return HttpResponseRedirect(reverse('user:home'))
		else:
			return HttpResponseRedirect(next)
	context = {
		"name_nav" : 'register',	
		"nbar" : "register",
		"form":form,
		'dbug' : dbug,
		'page' : 'full-page',
	}
	return render(request, 'accounts/login.html', context)

def logout_view(request):
	logout(request)
	return redirect('/')

@login_required
def user_settings(request):
	user = request.user

	try:
		twitter_login = user.social_auth.get(provider='twitter')
	except UserSocialAuth.DoesNotExist:
		twitter_login = None

	can_disconnect = (user.social_auth.count() > 1 or user.has_usable_password())

	return render(request, 'accounts/settings.html', {
		'twitter_login': twitter_login,
		'can_disconnect': can_disconnect
	})

@login_required
def user_password(request):
	if request.user.has_usable_password():
		PasswordForm = PasswordChangeForm
	else:
		PasswordForm = AdminPasswordChangeForm

	if request.method == 'POST':
		form = PasswordForm(request.user, request.POST)
		if form.is_valid():
			form.save()
			update_session_auth_hash(request, form.user)
			messages.success(request, 'Your password was successfully updated!')
			return redirect('password')
		else:
			messages.error(request, 'Please correct the error below.')
	else:
		form = PasswordForm(request.user)
	return render(request, 'accounts/password.html', {'form': form})	

accounts/templates/accounts/check_claim.html
{% extends 'index.html' %}
{% load static %}


{% block title %}
Claiming {{products_.product_name}} | {{ block.super }}
{% endblock %}

{% block header0 %}

{% endblock %}

{% block content_1 %}

<h3>{{products_.product_name}}</h3>
<hr>
<p>Product has been transfered to your account.</p>
{% endblock %}

accounts/templates/accounts/claim_list.html
{% extends 'index.html' %}
{% load static %}


{% block title %}
Page Text | {{ block.super }}
{% endblock %}

{% block header0 %}

{% endblock %}

{% block content_1 %}
<h3>Claimable Products:</h3>
{% for product in products_ %}
<p>{{product.product_name}}- <a href="{{ product.get_claim_url }}">Claim</a></p>

{% empty %}
<p>No claimable product.</p>
{% endfor %}
{% endblock %}

accounts/templates/accounts/claim_product.html
{% extends 'index.html' %}
{% load static %}
{% load secret_tag %}

{% block title %}
Page Text | {{ block.super }}
{% endblock %}

{% block header0 %}

{% endblock %}

{% block content_1 %}

<h3>{{products_.product_name}}</h3>
<hr>
{% if contacts_ %}
<p>posted on <b>{{ products_.timestamp }}</b></p>
<p>Posted by <b>{{ products_.user }}</b></p>
<p><i>Posted on behalf of its original creator</i></p>
<br>
<p>It remain in the original creator(s)'s interest to either claim this product as their own, or delete from this website.</p>
<div class="row">
	
	<div class="col">
		<p>This product is tagged with the following account(s)</p>
		<ul>
			{% for contact in contacts_ %}
			<li>{{contact.contact_type}} : {{contact.contact|show_last_string:3}}</li>
			{% endfor %}
		</ul>
	</div>
	<div class="col">
		<h5>How to claim?</h5>
		<br>
		<table class="table">
			<tbody>
				<tr>
					<td>Make an account on Basically Twins</td>
					<td>
						{% if request.user.is_authenticated %}
						<i class="fa fa-check"></i>
						{% else %}
						<a href="{% url 'register' %}">Register</a>
						{% endif %}

					</td>
				</tr>
				<tr>
					<td>Sync with twitter</td>
					<td>
						{% if twitter_login %}
						<i class="fa fa-check"></i>
						{% else %}
						<a href="{% url 'settings' %}">Check Here</a>
						{% endif %}
					</td>
				</tr>
				<tr>
					<td>Try Claiming</td>
					<td>
						{% if claim %}
						<a href="{% url 'user:check_claim' products_.slug request.user.username %}"> Check</a>
						{% else %}
						<p>You Cannot claim this product.</p>
						{% if twitter_login %}
						<p style="color: gray">You are Connected as <a href="https://twitter.com/{{ twitter_login.extra_data.access_token.screen_name }}/" target="_blank">@{{ twitter_login.extra_data.access_token.screen_name }}</a></p>
						{% else %}
						<p>You have not <a href="{% url 'login' %}">Logged in.</a></p>
						{% endif %}
						{% endif %}
					</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>

{% if request.user.is_authenticated %}
{% else %}
<p><u><a href="{% url 'register' %}">Login to claim!</a></u></p>
{% endif %}
<br>
<h3>Frequently Asked Questions</h3>
<hr>
<h4>what is Basically twins?</h4>
<p>Basically twins is a collection of profitable website. The main goal of this site is to help other entrepreneur find other websites which are profitable and decide which what they should do for their next idea.</p>
<h4>Why was this posted here?</h4>
<p>I, personally liked the product, and I felt more people should know about it. </p>
<h4>Who runs Basically Twins?</h4>
<p><a href="https://www.twitter.com/newlifeshoes">I run it</a>. :-). You can follow me on twitter to know more about me. <br>To be short, I am a jobless web developer who is stubborn enough to not find a job and work on projects which may or may not pay my bills.</p>

{% else %}

<p>This product is already claimed!</p>
<p>Please report to admin on <a href="https://www.twitter.com/newlifeshoes">twitter</a> if this is wrong</p>
{% endif %}


{% endblock %}

accounts/templates/accounts/login.html
{% extends 'index.html' %}
{% load static from staticfiles %}

{% block header0 %}
    <link href="{% static 'login/css/signin.css' %}" rel="stylesheet">
{% endblock %}

{% block title %}
    {{nbar}} | {{ block.super }}
{% endblock %}

{% block content_2 %}

<div style="margin-top: 150px" class="row"></div>

<div class="row">
</div>
<div class="container">
      <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4 text-center">
            {% if nbar == 'login' %}
                <h1 class="display-5" id="clocktext">
                    Login
                </h1>
                <h2 class="form-signin-heading"><small>Let's get back on track!</small></h2>
            {% elif nbar == 'register' %}
                <h1 class="display-5" id="clocktext">
                    Register
                </h1>
                <h2 class="form-signin-heading"><small>Let's Create your Free Account!</small></h2>
            {% endif %}
            <form class="form-signin" method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
                <br>
                {{ form }}
                <br>
                <br>
                <input type='submit' class='btn btn-lg btn-primary btn-block' name='next' value='{{ nbar }}'/>
            </form>
            <hr>
            <br>
            {% if nbar == 'login' %}
                <p>New Here? <a href="/register">Register!</a></p>
            {% elif nbar == 'register' %}
                <p>Looking to login? <a href="/login">Login!</a></p>
            {% endif %}
              <a href="{% url 'social:begin' 'twitter' %}">Login with Twitter</a>


            
        </div>
    </div>
</div>


<div style="margin-top: 200px" class="row"></div>

{% endblock %}

accounts/templates/accounts/password.html
{% extends 'index.html' %}
{% load static %}


{% block title %}
Change Password | {{ block.super }}
{% endblock %}

{% block header0 %}

{% endblock %}

{% block content_1 %}

<h2>Change Password</h2>
{% if not user.has_usable_password %}
<p style="color: red">You have not defined a password yet.</p>
{% endif %}
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">Save changes</button>
</form>
{% endblock %}

accounts/templates/accounts/settings.html
{% extends 'index.html' %}
{% load static %}


{% block title %}
Settings | {{ block.super }}
{% endblock %}

{% block content_1 %}
<h2>Settings</h2>

<h3>Twitter</h3>
{% if twitter_login %}
	<p>Connected as <a href="https://twitter.com/{{ twitter_login.extra_data.access_token.screen_name }}/" target="_blank">@{{ twitter_login.extra_data.access_token.screen_name }}</a></p>
	{% if can_disconnect %}
		<form method="post" action="{% url 'social:disconnect' 'twitter' %}">
			{% csrf_token %}
			<button type="submit">Disconnect from Twitter</button>
		</form>
	{% else %}
		<button type="button" disabled>Disconnect from Twitter</button>
		<p style="color: red">You must <a href="{% url 'password' %}">define a password</a> for your account before disconnecting from Twitter.</p>
		{% endif %}
	{% else %}
	<a href="{% url 'social:begin' 'twitter' %}">Connect to Twitter</a>
{% endif %}

<h3>Password</h3>
<a href="{% url 'password' %}">Manage your password</a>
{% endblock %}