basicallytwins/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accounts.views import (login_view, logout_view, register_view, user_settings, user_password)
from core.views import (index, list_one, list_one_new)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('list/realmoney/', list_one, name='list_one'),
    path('list/realmoney/new', list_one_new, name='list_one_new'),

    path('settings/', user_settings, name='settings'),
    path('settings/password/', user_password, name='password'),

    path('oauth/', include('social_django.urls', namespace='social')),  # <--
    
    path('', include('core.urls', namespace='user')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.lander , name='lander'),
    path('products/', views.index, name='home'),
    
    path('catagory/', include([
        path('', views.catagory_list, name='catagory_list'),
        path('<slug:slug>/', views.catagory_detail, name='catagory_detail'),
        ])),
 
	path('ads/<int:id>/', views.advert_redirect, name='advert_redirect'),    

    path('@<str:username>/', include([
        path('', views.user_profile, name='user_profile'),
        path('create_product', views.create_product, name='create_product'),
        path('admin_create_product', views.admin_create_product, name='admin_create_product'),
        path('all_advert', views.all_advert, name='all_advert'),
        path('create_advert', views.create_advert, name='create_advert'),
        path('edit_advert', views.edit_advert, name='edit_advert'),
        ])),
    # path('new', views.card_create, name='card_create'),
    # path('news', views.fetch_news, name='fetch_news'),
	
    path('tags/', include([
		path('', views.all_tags, name='all_tags'),
		path('<slug:slug>/', views.tag_detail, name='tag_detail'),
		])),

    path('product/<slug:slug>/', views.product_detail, name='product_detail'),
    path('product/<slug:slug>/<str:username>/edit', views.edit_product, name='edit_product'),
    path('product/<slug:slug>/<str:username>/delete', views.delete_product, name='delete_product'),
    path('claim_products/', views.claim_list, name='claim_list'),
    path('claim_products/<slug:slug>/', views.claim_product, name='claim_product'),
    path('claim_products/<slug:slug>/@<str:username>/', views.check_claim, name='check_claim'),
    
]

core/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.core.validators import URLValidator

import uuid
import random
from datetime import datetime, timedelta

def upload_location(adverts, filename):
	return "%s/%s/%s/%s" %(adverts.app_name, adverts.customer.product_name, adverts.user, filename)

def suggest_product():
	names = ['Bit translator', 'hoboprinter', 'Phone Smith',
				'Rock anne Role', 'Traders Back', 'Vortex Ship',
				'Rings of Bong', 'BlueSkin', 'Trackin', 
				'Wild flips', 'Cube box', 'Train Fins',
				'Glowing Bulb', 'Eurika', 'Bit Moment',
				'Stick ship', 'Reavling', 'Measurant',
				'Thin Gap', 'Spinning Floor', 'Callar']

	return(random.choice(names))

def unique_link_element():
	uid = uuid.uuid4()
	unque = uid.hex
	return unque

class links(models.Model):
	PLATFORM = (
		('Android', 'android'),
		('iOS', 'ios'),
		('Website', 'website'),
		('Chrome Extension', 'chrome'),
		)
	user					=			models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)
	platform				=			models.CharField(max_length=30, choices=PLATFORM, default=PLATFORM[0][0])
	link 					=			models.CharField(max_length=1000, blank=False, null=False)
	social_connection		=			models.ForeignKey('product', related_name='social_links', on_delete=models.CASCADE)

	def __str__(self):
		return (str(self.platform) + str(" for ") + str(self.social_connection))

	class Meta:
		verbose_name 		= 			"Link"
		verbose_name_plural = 			"Links"

class tags(models.Model):
	tag 					=			models.CharField(max_length=30, blank=False, null=False)
	slug 					=			models.SlugField(max_length=255, unique=True)

	timestamp				=			models.DateTimeField(auto_now=False, auto_now_add=True)
	updated					=			models.DateTimeField(auto_now=True, auto_now_add=False)

	# def get_absolute_url(self):
	# 	return reverse("user:tag", kwargs={"slug" : self.slug})
	def __str__(self):
		return (str(self.tag))
	class Meta:
		ordering 			=			["-timestamp", "-updated"]
		verbose_name 		=	 		"Tag"
		verbose_name_plural =	 		"Tags"

'''
	Each product is a website which has completed the following 
		1.	Started earning
		2.	Somerhing in common with a different company
		3. 	May or may not be VC funded
		4.	May or may not be Bootstrapped
	

	Each Product MUST be linked to one or more product, via twin Field.
	This is the sole of this website
'''
class email_list(models.Model):
	email 					=			models.EmailField(max_length=100 ,unique=True)
	timestamp				=			models.DateTimeField(auto_now=False, auto_now_add=True)
	updated					=			models.DateTimeField(auto_now=True, auto_now_add=False)

	# def get_absolute_url(self):
	# 	return reverse("user:tag", kwargs={"slug" : self.slug})
	def __str__(self):
		return (str(self.email))
	class Meta:
		ordering 			=			["-timestamp", "-updated"]
		verbose_name 		= 			"Email List"
		verbose_name_plural = 			"Email Lists"

class revenue_source(models.Model):
	REV_SOURCE = (
		("------", "------"),
		("Advertisments", "Ads"),
		("Subscription", "subscription"),
		("One time Payment", "entry fees"),
		("eCommence", "eCommence"),
		("Service sales", "service sales"),
		("Digital Product sales", "digital product sales"),
		("Digital Service sales", "digital service sales"),
		("Affiliate Marketing", 'Affiliate Marketing'),
		)
	source 					=			models.CharField(max_length=50, choices=REV_SOURCE, default=REV_SOURCE[0][0])

	def __str__(self):
		return(str(self.source))

class anon_user_detail(models.Model):
	CONTACTS_LIST = (
		('Twitter', 'twitter'),
		('e-mail', 'email'),
		)
	contact					=			models.CharField(max_length=200, blank=False, null=False)
	contact_type			=			models.CharField(max_length=30, choices=CONTACTS_LIST, default=CONTACTS_LIST[0][0])
	connected_product		=			models.ForeignKey('product', related_name='product_connected', on_delete=models.CASCADE, default=1)
	
	def __str__(self):
		return(self.contact)

'''
class list_all(models.Model):
	user 					=			models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)
	list_name 				=			models.CharField(max_length=50, blank=False, null=False)
	slug					=			models.SlugField(max_length=255, unique=True)
	list_detail				=			models.TextField(max_length=280, blank=True, null=True, default="List details", help_text="List Pitch in less than 280 character")

	timestamp				=			models.DateTimeField(auto_now=False, auto_now_add=True)
	updated					=			models.DateTimeField(auto_now=True, auto_now_add=False)

	def __str__(self):
		return(self.catagory_name)

	def get_absolute_url(self):
		return reverse("user:catagory_detail", kwargs={'slug' : self.slug})

	class Meta:
		verbose_name 		= 			"Product Catagory"
		verbose_name_plural = 			"Product Catagories"

'''



class list_items(models.Model):
	REV_SOURCES = (
		('Advert', 'ad'),
		('Royalty', 'royalty'),
		('Marketplace', 'marketplace'),
		)

	WORK_FOR = (
		('Painter', 'Painter'),
		('Writers', 'Writers'),
		('Educator', 'Educator'),
		('Programmer', 'Programmer'),
		('Music Creator', 'Music Creator'),
		('Video Creator', 'Video Creator'),
		('Internet Entrepreneur', 'internet Entrepreneur'),
		)

	user 					=			models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)
	name 					=			models.CharField(max_length=50, blank=False, null=False)
	slug					=			models.SlugField(max_length=255, unique=True)
	detail					=			models.TextField(max_length=280, blank=True, null=True, default="Product details", help_text="Product Pitch in less than 280 character")
	link 					=			models.URLField(max_length=1000, blank=False, null=False, help_text="URL")
	revenue_source			=			models.CharField(max_length=100, choices=REV_SOURCES, default=REV_SOURCES[0][0])
	suitable_for			=			models.CharField(max_length=100, choices=WORK_FOR, default=WORK_FOR[0][0])
	public_view				=			models.BooleanField(default=True)
	# sources
	# list_name 				=			models.ForeignKey(product_catagory, related_name='catagory', default=1, on_delete=models.CASCADE)


	timestamp				=			models.DateTimeField(auto_now=False, auto_now_add=True)
	updated					=			models.DateTimeField(auto_now=True, auto_now_add=False)

	def __str__(self):
		return(self.name + str(" By ") + self.user.username)

	def get_absolute_url(self):
		return reverse("user:product_detail", kwargs={"slug" : self.slug})


	class Meta:
		ordering	 		=			["-timestamp", "-updated"]
		verbose_name 		= 			"List"
		verbose_name_plural = 			"Lists"




class product_catagory(models.Model):
	PRODUCT_CAT = (
		("Virtual Reality", "VR"),
		("Argument Reality", "AR"),
		("Analytics", "analytics"),
		("Video Sharing", "video sharing"),
		("audio books", "audio books"),
		)
	catagory_name			=			models.CharField(max_length=50, blank=False, null=False, default=suggest_product())
	catagory_pitch			=			models.TextField(max_length=280, blank=True, null=True, default="Our revolutionary product will change the world", help_text="Catagory Detail")
	slug					=			models.SlugField(max_length=255, unique=True)
	# This field is to parse common words from the connected product's pitch.
	popular					=			models.TextField(max_length=1000, blank=True, null=True)
	UserBase				=			models.IntegerField(blank=True, null=True, default='0')
	total_revenue			= 			models.IntegerField(blank=True, null=True, default='0')
	avg_revenue				= 			models.IntegerField(blank=True, null=True, default='0')
	high_revenue			= 			models.IntegerField(blank=True, null=True, default='0')
	timestamp				=			models.DateTimeField(auto_now=False, auto_now_add=True)
	updated					=			models.DateTimeField(auto_now=True, auto_now_add=False)

	def __str__(self):
		return(self.catagory_name)

	def get_absolute_url(self):
		return reverse("user:catagory_detail", kwargs={'slug' : self.slug})

	class Meta:
		verbose_name 		= 			"Product Catagory"
		verbose_name_plural = 			"Product Catagories"


class product(models.Model):
	REV_INFO_SOURCE = (
		("from the Internet, unverified.", "internet, unverified"),
		("from the Internet, Admin Verified.", "internet, admin verified"),
		("verified by the Maker.", "maker verified"),
		("not for Public Viewing", "Not for public viewing"),
		)
	# who is uploading this product
	user					=			models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)
	# the product name
	product_name			=			models.CharField(max_length=50, blank=False, null=False, default=suggest_product())
	product_pitch			=			models.TextField(max_length=280, blank=True, null=True, default="Our revolutionary product will change the world", help_text="Product Pitch in less than 280 character")

	# To Avoid spam content
	no_spam					=			models.BooleanField(default=False)
	# If the product is uploaded by the maker, this needs to be done manually.
	product_verified 		=			models.BooleanField(default=False)
	slug					=			models.SlugField(max_length=255, unique=True)
	monthly_revenue			=			models.IntegerField(blank=False, null=False, default=0, help_text="Product's Current Monthly Revenue in USD. Enter '0' if product is in development phase.")
	# Added this on request of visitors
	revenue_source			=			models.ManyToManyField('revenue_source', blank=False, help_text='How do you get the revenue? please choose atleast one')
	revenue_info_source		=			models.CharField(max_length=50, choices=REV_INFO_SOURCE, default=REV_INFO_SOURCE[0][0])
	# the website url
	website					=			models.URLField(max_length=1000, blank=False, null=False, help_text="Your Landing page URL. When you choose to advert, your advert will divert to this URL.")
	# other website which are twins to this
	claimable				=			models.BooleanField(default=False)
	twin					=			models.ManyToManyField('product', blank=True, help_text="Websites which are very similar to your website.")
	tag 					=			models.ManyToManyField('tags', blank=True, help_text="Features your website offers.")

core/forms.py
from django import forms
from django.forms.formsets import BaseFormSet

from .models import product, adverts, tags, links, email_list, revenue_source, anon_user_detail, list_items
# from pagedown.widgets import PagedownWidget


# form to create a new product
class EmailForm(forms.ModelForm):
    class Meta:
        model = email_list
        fields = [
        "email",
        ]

# Form to create a new entry for List
class ListOneForm(forms.ModelForm):
    class Meta:
        model = list_items
        fields = [
        "name",
        "detail",
        "link",
        "revenue_source",
        "suitable_for",
        ]        
# form to create advert
class AdvertForm(forms.ModelForm):

    class Meta:
        model = adverts;
        fields = [
        "customer",
        "ad_words",
        "advert_text",
        "image",        
        "advert_lifespan",
        ]

# form to create a new product
class ProductForm(forms.ModelForm):
    # twin = forms.ModelMultipleChoiceField(queryset = product.objects.all(), widget=forms.CheckboxSelectMultiple())
    revenue_source = forms.ModelMultipleChoiceField(queryset = revenue_source.objects.all(), widget=forms.CheckboxSelectMultiple())
    # tags = forms.ModelMultipleChoiceField(queryset = taggers.objects.all(), widget=forms.CheckboxSelectMultiple())
    class Meta:
        model = product
        fields = [
        "catagory",
        "product_name",
        "product_pitch",
        "website",
        "monthly_revenue",
        "revenue_source",
        # "twin",
            ]
    
    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        # self.fields["revenue_source"].default = [0][0] 
        self.fields["revenue_source"].help_text = "Please select atleast one" 
        # self.fields["twin"].required = False 

# FORM FOR INDIVIDUAL LINKS
class NewDetailForm(forms.Form):
    contact  = forms.CharField(
                    max_length=50,
                    widget=forms.TextInput(attrs={
                            'placeholder' : 'Please enter the credentials'
                        }), 
                    required=False)

    contact_type = forms.ChoiceField(choices=anon_user_detail.CONTACTS_LIST, required=True)

class BaseDetailFormSet(BaseFormSet):
    def clean(self):
        """
        Adds validation to check that no two links have the same contact or URL
        and that all links have both an contact and URL.
        """
        if any(self.errors):
            return

        contacts = []
        contact_types = []
        duplicates = False

        for form in self.forms:
            if form.cleaned_data:
                contact = form.cleaned_data['contact']
                contact_type = form.cleaned_data['contact_type']

                # Check that no two links have the same contact or URL
                if contact and contact_type:
                    if contact in contacts:
                        duplicates = True
                    contacts.append(contact)

                    contact_types.append(contact_type)

                if duplicates:
                    raise forms.ValidationError(
                        'Links must have unique Names and URLs.',
                        code='duplicate_links'
                    )
"""
                # Check that all links have both an contact and URL
                if contact_type and not contact:
                    raise forms.ValidationError(
                        'All links must have an contact.',
                        code='missing_anchor'
                    )
                elif contact and not contact_type:
                    raise forms.ValidationError(
                        'All links must have a contact_type.',
                        code='missing_URL'
                    )
"""

core/templates/core/all_adverts.html
{% extends 'index.html' %}
{% load static %}


{% block title %}
Your Adverts | {{ block.super }}
{% endblock %}

{% block header0 %}
<style type="text/css">
div.price-sheet{
	min-height: 200px;
	width: 100%;
	border-radius: 10px;
	background: #1E1E24;
	margin: 20px;
	color: white;
	text-align: center;
}
div.price-sheet .title-row{
	border-radius: 10px 10px 0px 0px;
	padding-top: 20px;
	background: #92140C;
}
div.price-sheet .decription-row{
	margin-top: 20px;
	margin-bottom: 20px;
}

div.hide-this {
	visibility: collapse;
}
</style>
{% endblock %}

{% block content_1 %}
<div class="row">
	<div class="col">

		<a class="pull-left">
			<h3>
				Adverts
			</h3>
		</a>
		<a style="margin-bottom: 20px" href="{% url 'user:create_advert' request.user.username %}" class="btn btn-outline-primary btn-lg pull-right" role="button">Buy New Advert</a>
		
	</div>
</div>

<table class="table table-striped">
	<thead>
		<tr>
			<th>Advert ID</th>
			<th>Product</th>
			<th>Last Updated</th>
			<th>Viewed</th>
			<th>Clicked</th>
			<th>Advert Lifespan</th>
			<th>Status</th>
		</tr>
	</thead>
	<tbody>
		{% for advert in all_adverts %}
		<tr>
			<td>{{advert.id}}</td>
			<td>{{advert.customer.product_name}}</td>
			<td>{{advert.updated}}</td>
			<td>{{advert.advert_view}}</td>
			<td>{{advert.current_clicks}}</td>
			<td>{{advert.advert_lifespan}} Day{{ advert.advert_lifespan|pluralize }}</td>
			<td>{{advert.advert_status}}</td>
		</tr>
		{% empty %}
		<td colspan="7"><p class="lead" style="text-align: center;">You have not placed any adverts yet.</p></td>
		{% endfor %}
	</tbody>
</table>
<section>
	<div class="row">
		<div class="col">
			<h3>Price Sheet</h3>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-3 col-md-3 col-sm-12 price-sheet">
			<div class="row title-row">
				<div class="col">
					<h4>One day</h4>
					<i class="fa fa-star" aria-hidden="true"></i>

					<p style="visibility: hidden;">Small Shots</p>
				</div>
			</div>
			<div class="row description-row">
				<div class="col">
					<p class="lead"><b>1</b> day</p>
				</div>
			</div>
			<div class="row description-row">
				<div class="col">
					<p class="lead">Text - $5</p>
				</div>
				
			</div>
			<div class="row description-row">
				<div class="col">
					<p class="lead">Image - $10</p>
				</div>
				
			</div>			
		</div>


		<div class="col-lg-4 col-md-3 col-sm-12 price-sheet">
			<div class="row title-row">
				<div class="col">
					<h4>Single Week</h4>
					<i class="fa fa-star" aria-hidden="true"></i>
					<i class="fa fa-star" aria-hidden="true"></i>
					<i class="fa fa-star" aria-hidden="true"></i>
					<p>Best Value</p>
				</div>
			</div>
			<div class="row description-row">
				<div class="col">
					<p class="lead"><b>7</b> days</p>
				</div>
			</div>
			<div class="row description-row">
				<div class="col">
					<p class="lead">Text - $25</p>
				</div>
				
			</div>
			<div class="row description-row">
				<div class="col">
					<p class="lead">Image - $50</p>
				</div>
				
			</div>			
		</div>


		<div class="col-lg-3 col-md-3 col-sm-12 price-sheet">
			<div class="row title-row">
				<div class="col">
					<h4>A Month</h4>
					<i class="fa fa-star" aria-hidden="true"></i>
					<i class="fa fa-star" aria-hidden="true"></i>

					<p style="visibility: hidden;">Long term</p>					
				</div>
			</div>
			<div class="row description-row">
				<div class="col">
					<p class="lead"><b>28</b> days</p>
				</div>
			</div>
			<div class="row description-row">
				<div class="col">
					<p class="lead">Text - $140</p>
				</div>
	
			</div>
			<div class="row description-row">
				<div class="col">
					<p class="lead">Image - $280</p>
				</div>
	
			</div>			
		</div>


	</div>
</section>
{% endblock %}

core/templates/core/product_detail.html
{% extends 'index.html' %}
{% load static %}
{% load humanize %}


{% block title %}
{{product.product_name}} | {{ block.super }}
{% endblock %}

{% block header0 %}
<style type="text/css">
/* The heart of the matter */
div.testimonial-group > div.row {
	overflow-x: auto;
	white-space: nowrap;
}
div.testimonial-group > div.row > div.twin-products {
	display: inline-block;
	float: none;
}

/* Decorations */
div.twin-products {
	border-radius: 10px;
	color: #c69;
	font-size: 20px;
	padding: 20px;
	outline: thin;
	border: 1px solid red;
	outline-color: #c69;
	margin: 10px;
}
div.inspired-twin-products {
	border-radius: 10px;
	font-size: 28px;
	padding: 20px;
	background: #c69;
	margin: 10px;
}

div.inspired-twin-products > a{
	color: #fff;
}
div.inspired-twin-products > p {
	color: #fff;
}

div.inspired-twin-products > a.maker {
	font-size: 20px;
}

a.user-product{
	margin-left: 5px;
	margin-right: 5px;
}
</style>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
{% endblock %}

{% block content_1 %}
<div class="row">
	<div class="col-lg-3 col-md-3 col-sm-3">
		<div class="product-image">
			<img src="https://placeimg.com/140/140/tech/grayscale">
		</div>
	</div>
	<div class="col">
		<div class="col-lg-12 col-md-12 col-sm-12">
			{% if product.product_verified %}
			<h1 class="pull-right" style="color: blue; font-size: 0.7em">
				<i class="fa fa-certificate fa-lg" style="color: blue" aria-hidden="true"></i> VERIFIED
			</h1>
			{% endif %}
			{% if request.user == product.user %}
			<h4 class="pull-right">
<!-- 				<a href="{% url 'user:delete_product' product.slug request.user.username %}" class="btn btn-danger btn-sm pull-right user-product" role="button">delete</a> -->
				<a href="{% url 'user:edit_product' product.slug request.user.username %}" class="btn btn-outline-danger btn-sm pull-right user-product" role="button">Edit</a>
			</h4>
			{% endif %}
			<h1>
				{{product.product_name}} 
			</h1>
		</div>
		<div class="col-lg-12 col-md-12 col-sm-12" style="float: left">
			<div class="row rounded product-detail">
				<div class="col">
					<p>{{product.product_pitch}}</p>
				</div>
			</div>			
			<div class="row rounded product-detail">
				<div class="col">
					<b>Revenue: </b>
					<p>${{product.monthly_revenue|intcomma}} /month</p>

				</div>
				<div class="col-sm-12 col-lg-12 col-md-12">
					{% for source in product.revenue_source.all %}
					<a style="margin-right: 5px" href="" class="btn btn-outline-primary btn-sm" role="button">{{ source.source }}</a>
					{% endfor %}
				</div>
				<div class="col-lg-12 col-md-12 col-sm-12">
					<p class="shadow-text"><b>Note :</b> the revenue details are {{product.revenue_info_source}}</p>
				</div>
			</div>
			<div class="row rounded product-detail">
				<div class=" product-link-list rounded" style="float: right;">
					{% for link in links_ %}

					{% if link.social_connection == product %}

					{% if link.get_platform_display == 'ios' %}
					<a href="{{link.link}}" target="_blank"><i class="fa fa-lg fa-apple" style="margin: 5px"></i> iOS App</a><br>
					{% endif %}

					{% if link.get_platform_display == 'android' %}
					<a href="{{link.link}}" target="_blank"><i class="fa fa-lg fa-android" style="margin: 5px"></i> Android App</a><br>
					{% endif %}

					{% if link.get_platform_display == 'website' %}
					<a href="{{link.link}}" target="_blank"><i class="fa fa-lg fa-home" style="margin: 5px"></i> Webpage</a><br>
					{% endif %}

					{% if link.get_platform_display == 'chrome' %}
					<a href="{{link.link}}" target="_blank"><i class="fa fa-lg fa-chrome" style="margin: 5px"></i> Chrome Extension</a><br>
					{% endif %}

					{% endif %}
					{% endfor %}
					<a href="{{product.website}}" target="_blank"><i class="fa fa-lg fa-home" style="margin: 5px"></i> Website</a><br>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="row" style="margin-top: 20px; visibility: hidden;">
	<div class="col-lg-12 col-md-12 col-sm-12">
		<div class="row rounded product-detail">
			<div class="col">
				<b>Tags: </b>
				{% if product.tag %}
				{% for tag in product.tag.all %}
				<a style="margin-right: 5px" href="" class="btn btn-outline-primary btn-sm" role="button">{{ tag.tag }}</a>
				{% endfor %}
				{% endif %}
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12">
		<div class="row rounded product-details" style="margin-top: 20px; visibility: visible;">
			<div class="col-lg-12 col-md-12 col-sm-12">
				<h4 class="pull-right"><a href="{{ product.catagory.get_absolute_url }}">View Market</a></h4>
				<h4><b>Market Place </b></h4>
			</div>
			<div class="container testimonial-group">

				<canvas id="pie-chart" width="800" height="450"></canvas>
				<script>
					new Chart(document.getElementById("pie-chart"), {
						type: 'pie',
						data: {
							labels: ["{{product.product_name}}",
							
							{% for product in this_catagory %}

							"{{product.product_name}}",

							{% endfor %}

							],
							datasets: [{
								label: "Revenue (USD/Month)",
								backgroundColor: ["#4B4E6D",
								
								{% for product in this_catagory %}

								"#99A1A6",

								{% endfor %}

								

								],
								data: [
								{{product.monthly_revenue}},
								
								{% for product in this_catagory %}

								{{product.monthly_revenue}},

								{% endfor %}
								

								]
							}]
						},
						options: {
							title: {
								display: true,
								text: 'Total Revenue generated By products in Similar Segment (USD/Month)'
							}

						}
					});					
				</script>


			</div>
		</div>


		<div class="row rounded product-details"  style="margin-top: 20px">
			<div class="col-lg-2 col-md-12 col-sm-12">
			</div>
			<div class="container testimonial-group">
				<h4><b>{{product.product_name}} was inspired by</b></h4>
				<div class="row text-center">
					{% for product in product.twin.all %}
					<div class="twin-products">
						<a href="{{product.get_absolute_url}}"><p>{{product.product_name}}</p></a>
						<a class="maker" href="{% url 'user:user_profile' product.user.username %}"><sup>by {{product.user.username}}</sup></a>
						<p class="lead">${{product.monthly_revenue|intcomma}} /month</p>
					</div>

					{% empty %}
					<div class="twin-products">
						This product is unique!						
					</div>
					{% endfor %}
				</div>

				<h4 style="margin-top: 10px"><b>Products inspired by {{product.product_name}}</b></h4>

				<div class="row text-center">
					{% for twin in inspired_twins.all %}
					<div class="inspired-twin-products">
						<a href="{{twin.get_absolute_url}}"><p>{{twin.product_name}}</p></a>
						<a class="maker" href="{% url 'user:user_profile' twin.user.username %}"><sup>by {{twin.user.username}}</sup></a>
						<p class="lead">${{twin.monthly_revenue|intcomma}} /month</p>
					</div>
					{% empty %}
					<div class="inspired-twin-products">
						This product is unique!						
					</div>
					{% endfor %}
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

core/templates/core/twinslist.html
{% extends 'index.html' %}
{% load static %}


{% block title %}
	{{ block.super }}
{% endblock %}


{% block content_1 %}

{% endblock %}