basicallytwins/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accounts.views import (login_view, logout_view, register_view, user_settings, user_password)
from core.views import (index, list_one, list_one_new)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('list/realmoney/', list_one, name='list_one'),
    path('list/realmoney/new', list_one_new, name='list_one_new'),

    path('settings/', user_settings, name='settings'),
    path('settings/password/', user_password, name='password'),

    path('oauth/', include('social_django.urls', namespace='social')),  # <--
    
    path('', include('core.urls', namespace='user')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.lander , name='lander'),
    path('products/', views.index, name='home'),
    
    path('catagory/', include([
        path('', views.catagory_list, name='catagory_list'),
        path('<slug:slug>/', views.catagory_detail, name='catagory_detail'),
        ])),
 
	path('ads/<int:id>/', views.advert_redirect, name='advert_redirect'),    

    path('@<str:username>/', include([
        path('', views.user_profile, name='user_profile'),
        path('create_product', views.create_product, name='create_product'),
        path('admin_create_product', views.admin_create_product, name='admin_create_product'),
        path('all_advert', views.all_advert, name='all_advert'),
        path('create_advert', views.create_advert, name='create_advert'),
        path('edit_advert', views.edit_advert, name='edit_advert'),
        ])),
    # path('new', views.card_create, name='card_create'),
    # path('news', views.fetch_news, name='fetch_news'),
	
    path('tags/', include([
		path('', views.all_tags, name='all_tags'),
		path('<slug:slug>/', views.tag_detail, name='tag_detail'),
		])),

    path('product/<slug:slug>/', views.product_detail, name='product_detail'),
    path('product/<slug:slug>/<str:username>/edit', views.edit_product, name='edit_product'),
    path('product/<slug:slug>/<str:username>/delete', views.delete_product, name='delete_product'),
    path('claim_products/', views.claim_list, name='claim_list'),
    path('claim_products/<slug:slug>/', views.claim_product, name='claim_product'),
    path('claim_products/<slug:slug>/@<str:username>/', views.check_claim, name='check_claim'),
    
]

templates/footer.html
	<!-- Footer -->
	<footer class="footer-class">
		<div class="container-fluid">
			<div class="container">
				<div class="row">
					<div class="col-lg-4 rounded" style="margin-top: 10px">
						<h4>Credits</h4>
						<hr>
						<p><i class="fa fa-lg fa-pie-chart" aria-hidden="true"></i> Graphs by : <a href="http://www.chartjs.org/">Charts.js</a></p>
						<p><i class="fa fa-lg fa-font-awesome" aria-hidden="true"></i> Fonts by : <a href="http://fontawesome.io/">Font Awesome</a></p>
						<p><i class="fa fa-lg fa-picture-o" aria-hidden="true"></i> Dummy Thunbnail by : <a href="https://placeimg.com/">placeimg</a></p>
						<p><i class="fa fa-lg fa-picture-o" aria-hidden="true"></i> Landing page Image by : <a href="https://www.pexels.com/">pexels</a></p>
						<p><i class="fa fa-lg fa-file-text" aria-hidden="true"></i> Bootstrap Templates from : <a href="https://startbootstrap.com/template-categories/all/">startbootstrap</a></p>
					</div>
					<div class="col-lg-4 rounded" style="margin-top: 10px">
						<h4>Important Note:</h4>
						<hr>
						<ul>
							<li>
								<p>
									Basically twins or <a href="https://www.twitter.com/NewLifeShoes">Ali</a> does not formally represent the companies or products listed on <a href="{% url 'user:home' %}">this</a> website, unless stated otherwise.
								</p>
							</li>
							<li>
								<p>
									The revenue stated on the products details page or product list page, may or may not be true to their nature, unless stated otherwise.
								</p>
							</li>
						</ul>
					</div>
					<div class="col-lg-4 rounded" style="margin-top: 10px">
						<h4>Dear User:</h4>
						<hr>
						<p>If you find any product or company is fake or belongs to you, please <a href="https://twitter.com/NewLifeShoes" target="_blank">tweet</a> me ASAP.</p>
						<br>

						<p>Claim a product on this site? <a href="{% url 'user:claim_list' %}">Click here</a></p>

							<a href="https://twitter.com/intent/tweet?screen_name=newlifeshoes&ref_src=twsrc%5Etfw" class="twitter-mention-button" data-show-count="false">Suggestions? Tweet me</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

					</div>
				</div>
			</div>
			<!-- /.container -->
		</div>
		<div class="col-lg-12 footer-lower" >
			<p>Created and Maintained by <a href="https://twitter.com/NewLifeShoes" target="_blank"><i class="fa fa-lg fa-twitter" aria-hidden="true"></i>
			Ali Khundmiri</a></p>
			<p>All rights reserved 2018 by Ali khundmiri</p>
		</div>

	</footer>

templates/general_form.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
{{top_text}} | {{ block.super }}
{% endblock %}

{% block header0 %}
{{ form.media }}
{% endblock %}

{% block content_1 %}
<div class="row">
	<div class="col">
		<h3>{{top_text}}</h3>
		<h3><small>{{form_text}}</small></h3>
	</div>
</div>
<div class="row">
	<div class="col">
		<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
			{{ form|crispy }}
			<input type='submit' class='btn btn-outline-primary btn-lg' value='{{ tab_text }}'/>
		</form>		
	</div>
</div>

{% endblock %}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="{% block meta_description %}{% endblock %}">
	<meta name="author" content="{% block meta_author %}{% endblock %}">
		

	<title>
		{% block title %} 
		Basically Twins | Because Free Market.
		{% endblock %}
	</title>
	<link rel="shortcut icon" type="image/png" href="{% static 'base/favicon/favicon.ico' %}"/>

	<!-- Bootstrap core CSS -->
	<link href="{% static 'base/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

	<!-- Custom fonts for this template -->
	<link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

	<!-- Custom styles for this template -->
	<link href="{% static 'base/css/one-page-wonder.min.css' %}" rel="stylesheet">

	<link rel="stylesheet" href="{% static 'fontawesome/css/font-awesome.min.css' %}">
	

	<style>
	body {
		/*overflow: hidden;*/
		padding-top: 100px;
		/*background: #331832 !important;*/
			/* Adding !important forces the browser to overwrite the default style 
			applied by Bootstrap */
			/*color : #FCEAEA;*/
			/*Div of Cards, align center */
			/*display:flex;*/
		}
		p.right-top-text{
			color: #28262C;
		}
		a.right-bottom-text{
			color: #9C9C9C;
			text-decoration: none;
		}
		a.right-bottom-text:hover{
			color: #4F4268;
			text-decoration: none;
		}
		a.right-bottom-text:active{
			color: #211D28;
			text-decoration: none;
		}

		.product-line:nth-child(odd) {
			background: #FFF2F1;
		}

		.product-line:nth-child(even) {
			background: #FFF2FF;
		}

		div.advert-self {
			height: 150px;
			width: 300px;
			margin-top: 20px;
			vertical-align: middle;
			text-align: center;
			background: #FFF6F1;
		}
		div.advert {
			width: 100%;
			margin-bottom: 20px;
			vertical-align: middle;
			text-align: center;
		}

		div.advert:nth-child(3n+0) {
			background: #FFF6F1;
		}

		div.advert:nth-child(3n+1) {
			background: #FFF2F1;
		}

		div.advert:nth-child(3n+2) {
			background: #FFD2F1;
		}
		
		p.advert-text{
			padding-top: 0px;
		}
		.learn-more-text{
			padding-bottom: 20px;
		}
		img.image-advert{
			height: 100%;
			width: 100%;
			padding: 5px;
			padding-top: 0px;
			box-shadow: currentColor;
		}
		p.advert-sponsored{
			font-size: 12px; 
			text-align:right; 
			margin-right: 5px;
			color: #9C9C9C;
		}
		p.shadow-text {
			color: #99A1A6;
		}

		.footer-class{
			padding-top: 3rem !important;
			background: #122C34;
			color: #EDDEDE;
		}

		.footer-class a{
			color: #C6B1D5;	
		}

		.footer-lower {
			text-align: center; 
			padding-top: 10px;
			padding-bottom: 10px;
			background: #162E3D;
		}


	</style>

	{% block header0 %}

	{% endblock %}

	
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-113036538-1"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'UA-113036538-1');
	</script>
	<!-- Facebook Pixel Code -->
	<script>
		!function(f,b,e,v,n,t,s)
		{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
			n.callMethod.apply(n,arguments):n.queue.push(arguments)};
			if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
			n.queue=[];t=b.createElement(e);t.async=!0;
			t.src=v;s=b.getElementsByTagName(e)[0];
			s.parentNode.insertBefore(t,s)}(window, document,'script',
				'https://connect.facebook.net/en_US/fbevents.js');
			fbq('init', '196434251100195');
			fbq('track', 'PageView');
		</script>
		<noscript><img height="1" width="1" style="display:none"
			src="https://www.facebook.com/tr?id=196434251100195&ev=PageView&noscript=1"
			/>
		</noscript>
		<!-- End Facebook Pixel Code -->

	</head>

	<body>
		<!-- Navigation -->
		{% include 'navbar.html' %}
		{% if page == 'full-page' %}
		{% block content_2 %}
		{% endblock %}
		{% else %}
		<div class="container">
			<div class="row">
				<div class="col-lg-9 col-md-12 col-sm-12">
					<!-- content -->
					{% block content_1 %}
					{% endblock %}
				</div>
				<div class="col-lg-3 col-md-12 col-sm-12">
					<!-- content advert -->
					{% block content_3 %}
					{% endblock %}
					<div class="row">
						<div class="col">
							<p class="right-top-text">Featured Products</p>
							<!-- if featured products are available, place it, else, place our other website ad -->
							{% if ads %}
							{% for ad in ads %}
							<div class="rounded advert">
								{% if ad.image %}
								<!-- IMAGE AD HERE -->
								<p class="advert-sponsored for-image"><i>sponsored by {{ad.customer.product_name}}</i></p>
								<img class="image-advert" src="{{ad.image.url}}" height="100%", width="100%">
								{% elif ad.ad_words %}
								<!-- TEXT AD HERE -->
								<p class="advert-sponsored"><i>sponsored by {{ad.customer.product_name}}</i></p>
								<p class="advert-text">{{ad.ad_words}}</p>
								{% endif %}
								<i><a class="right-bottom-text learn-more-text" target="_blank" href="{% url 'user:advert_redirect' ad.id %}">{{ad.advert_text}}</a></i>
							</div>
							{% endfor %}
							{% endif %}
							{% comment %}
							<div class="rounded advert-self">
								<p class="advert-self-text">our custom advertisment</p>
							</div>
							{% endcomment %}	
							<a href="
							{% if request.user.is_authenticated %}
							{% url 'user:all_advert' request.user.username %}
							{% else %}
							{% url 'login'  %}
							{% endif %}
							" class="btn btn-dark btn-sm" style="float: right">Buy Ad space</a>
						</div>
					</div>
				</div>			
			</div>
		</div>
		{% endif %}

		<!-- footer -->
		<div style="margin-top: 20px"></div>
		{% include 'footer.html' %}

		<script type="text/javascript">
			$(function () {
				$('[data-toggle="tooltip"]').tooltip()
			})
		</script>

		<!-- Bootstrap core JavaScript -->
		<script src="{% static 'base/vendor/jquery/jquery.min.js' %}"></script>
		<script src="{% static 'base/vendor/bootstrap/js/bootstrap.bundle.js' %}"></script>
		<script src="{% static 'base/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
		<script type="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>

	</body>

	</html>

templates/lander.html
{% extends 'index.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block header0 %}
{{ form.media }}

<style>
body {
	padding-top: 0px !important;
}
p {
	line-height: 200%;

}
</style>
{% endblock %}
{% block content_2 %}
<header class="masthead text-center text-white">
	<div class="masthead-content">
		<div class="container">
			<h1 class="masthead-heading mb-0">Basically Twins</h1>
			<h4 class="masthead-subheading mb-0">Not all ideas are unique</h4>
			<a href="{% url 'user:home' %}" class="btn btn-primary btn-xl rounded-pill mt-5">Check out the website</a>
			<a href="{% url 'list_one' %}" class="btn btn-primary btn-xl rounded-pill mt-5">Check out the List</a>
		</div>
	</div>
	<div class="bg-circle-1 bg-circle"></div>
	<div class="bg-circle-2 bg-circle"></div>
	<div class="bg-circle-3 bg-circle"></div>
	<div class="bg-circle-4 bg-circle"></div>
</header>

<section>
	<div class="container">
		<div class="row align-items-center">
			<div class="col-lg-6 order-lg-2">
				<div class="p-5">
					<img class="img-fluid rounded-circle" src="{% static 'base/img/04.jpeg' %}" alt="">
				</div>
			</div>
			<div class="col-lg-6 order-lg-1">
				<div class="p-5">
					<h2 class="display-5">The <i>What</i> and The <i>Why</i>.</h2>
					<p>Every time I plan to create a new project, turns out there is someone else doing the same thing, and there is no way I can go head-to-head against them. <br>This forces me to do more deep study of the market to understand if its worth investing my time developing this product.<br><br> That's why Basically Twins was created, which as the name suggests, will show you the products which are very much similar to other mainstream products, but they have their own identity.</p>

				</div>
			</div>
		</div>
	</div>
</section>

<section>
	<div class="container">
		<div class="row align-items-center">
			<div class="col-lg-6">
				<div class="p-5">
					<h2 class="display-5">Why we need this website</h2>
					<p>We do not have to limit our self with a small piece of pie, when we can make as many pies as we like.</p>
					<br>
					<p>This crowd based website will hold the database to this massive community and our awesome products which solve problems ranging from daily work to automation.</p>
					<hr>
					<p>Check out this cool tweet by <a href="https://twitter.com/sehurlburt/">Stephanie Hurlburt</a></p>
				</div>
			</div>
			<div class="col-lg-6">
				<div class="p-5">
					<!-- <img class="img-fluid rounded-circle" src="{% static 'base/img/02.jpg' %}" alt=""> -->
					<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">I want to highlight this point:<br><br>There is enough room for 10 or even 100 people to exist in their own companies and make enough money to make a living while ALL MAKING THE SAME THING<br><br>So stop worrying about needing some magical unique idea no one else has and focus on business <a href="https://t.co/tYzmjfUXpa">https://t.co/tYzmjfUXpa</a></p>&mdash; Stephanie Hurlburt (@sehurlburt) <a href="https://twitter.com/sehurlburt/status/952013506273923072?ref_src=twsrc%5Etfw">January 13, 2018</a></blockquote>
					<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>					
				</div>
			</div>
		</div>
	</div>
</section>

<section>
	<div class="container">
		<div class="row align-items-center">
			<div class="col-lg-6 order-lg-2">
				<div class="p-5">
					<img class="img-fluid rounded-circle" src="{% static 'base/img/03.jpg' %}" alt="">
				</div>
			</div>
			<div class="col-lg-6 order-lg-1">
				<div class="p-5">
					<h2 class="display-5">How can this site help you?</h2>
					<p>With this website's crowd sourcing ability we can estimate the size of market for any idea by evaluating the size, growth and competition within existing players.<br><br>
					With such a tool, it will be much easier for companies, startup, bootstrappers and Venture Capitalist to validate new markets before even starting to build their product.</p>
				</div>
			</div>
		</div>
	</div>
</section>
<section>
	<div class="container">
		<div class="row align-items-center text-center">
			<div class="col-lg-12">
				
			</div>
		</div>
		<div class="row align-items-center">
			<div class="col-lg-6">
				<div class="p-5">
					<h4>Take a look!</h4>
					<a href="{% url 'user:home' %}" class="btn btn-primary btn-xl rounded-pill mt-5">Check out the website</a>
					<a href="{% url 'user:home' %}" class="btn btn-primary btn-xl rounded-pill mt-5">Signup</a>
					<a href="{% url 'user:home' %}" class="btn btn-primary btn-xl rounded-pill mt-5">Login</a>
				</div>
			</div>
			<div class="col-lg-6">
				<div class="p-5">
					<h4>Be a part of our community!</h4>
					<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
						{{ form|crispy }}
						<input type='submit' class='btn btn-outline-primary btn-lg' value='Keep me Updated'/>
					</div>
				</div>	
			</div>		
		</div>

	</section>
	{% endblock %}

templates/navbar.html
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
		<div class="container">
			<a class="navbar-brand" href="{% url 'user:lander' %}">Basically Twins<sub style="color: #92140C">ALPHA</sub></a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarResponsive">
				<ul class="navbar-nav mr-auto">
					{% if request.user.is_authenticated %}
					<li class="nav-item">
						<a class="nav-link" href="{% url 'user:create_product' request.user.username %}">create</a>
					</li>
					{% endif %}
					{% if request.user.is_superuser %}
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							Super Create
						</a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdown">
							<a class="dropdown-item" href="{% url 'user:admin_create_product' request.user.username %}">
								<i class="fa fa-user fa-fw" aria-hidden="true"></i>&nbsp; Anonymous create</a>
							<a class="dropdown-item" href="{% url 'list_one_new' %}">
								<i class="fa fa-cog fa-fw" aria-hidden="true"></i>&nbsp; New $ item </a>
						</div>
					</li>					
					{% endif %}
					<li class="nav-item">
						<a class="nav-link" href="{% url 'list_one' %}">List</a>
					</li>					
				</ul>
				<ul class="navbar-nav ml-auto">
					<li class="nav-item">
						<a class="nav-link" href="{% url 'user:home' %}">Products</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'user:catagory_list' %}">Categories</a>
					</li>
					{% if request.user.is_authenticated %}
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							@{{request.user.username}}
						</a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdown">
							<a class="dropdown-item" href="{% url 'user:user_profile' request.user.username %}">
								<i class="fa fa-user fa-fw" aria-hidden="true"></i>&nbsp; Profile</a>	
							<a class="dropdown-item" href="{% url 'settings' %}">
								<i class="fa fa-cog fa-fw" aria-hidden="true"></i>&nbsp; Settings</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" data-toggle="modal" data-target="#logout_modal" href="">
								<i class="fa fa-sign-out fa-fw" aria-hidden="true"></i>&nbsp; Logout</a>
						</div>
					</li>
					{% else %}
					<li class="nav-item">
						<a class="nav-link" href="{% url 'login' %}">Login</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'register' %}">Register</a>
					</li>
					{% endif %}
				</ul>
			</div>
		</div>
	</nav>

	<!-- Modal -->
	<div class="modal fade" id="logout_modal" tabindex="-1" role="dialog" aria-labelledby="logoutModalLabel" aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="logoutModalLabel">Logout</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					Are you sure you want to logout, {{request.user.username}}?
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
					<a href="{% url 'logout' %}" class="btn btn-outline-danger" role="button">Logout</a>
				</div>
			</div>
		</div>
	</div>

templates/sampletemplate.html
{% extends 'index.html' %}
{% load static %}


{% block title %}
Page Text | {{ block.super }}
{% endblock %}

{% block header0 %}

{% endblock %}

{% block content_1 %}

{% endblock %}

templates/testing.html
<!DOCTYPE html>
<html>
<head>
	<title>Welcome</title>
	<style type="text/css">
		body{
			background: #B0BCA9;
			color: #122C34;
		}
		<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">

	</style>
</head>
<body>
<h2>Welcome</h2>
<h1>Sup</h1>
</body>
</html>

templates/user_profile.html
{% extends 'index.html' %}
{% load static %}


{% block title %}
User Profile | {{ block.super }}
{% endblock %}


{% block header0 %}
<style type="text/css">
.product-line{
	padding: 20px
}
.product-line:nth-child(odd){
	background: #FFF2F1;
}
.product-line:nth-child(even){
	background: #FFF2FF;
}

a.top-deck{
	margin: 5px
}

a.right-deck{
	margin: 5px;
	font-size: 15px;
}

div.top-deck-col{
	padding-left: 0px !important;
	padding-right: 0px !important;
	margin-bottom: 20px;
}

a.user-product{
	margin-left: 5px;
	margin-right: 5px;
}
</style>
{% endblock %}


{% block content_1 %}
<div class="row">
	<div class="col top-deck-col">
		<a class="pull-left">
			<h3>
				{{username}}
			</h3>
		</a>
		<a href="{% url 'user:create_product' request.user.username %}" class="btn btn-outline-dark btn-lg pull-right top-deck" role="button">Add new Product</a>
		<a href="{% url 'user:create_advert' request.user.username %}" class="btn btn-outline-primary btn-lg pull-right top-deck" role="button">Create new advert</a>

	</div>
</div>
<div class="row">
	<div class="col">
		<!-- <p class="lead">@twitter</p> -->
		{% for product in products %}
		<div class="row">
			<div class="col rounded product-line" style="">
				{% if request.user == product.user %}
				<div class="col">
					{% if not product.no_spam %}
					<p class="lead" style="color: blue">Waiting for admin Aproval</p>
					{% endif %}

				</div>
				<h4 class="pull-right">
					<a href="{% url 'user:delete_product' product.slug request.user.username %}" class="btn btn-danger btn-sm pull-right user-product" role="button">delete</a>
					<a href="{% url 'user:edit_product' product.slug request.user.username %}" class="btn btn-outline-danger btn-sm pull-right user-product" role="button">Edit</a>
				</h4>
				{% endif %}
				<h4><a href="{{product.get_absolute_url}}">{{product.product_name}}</a>
					<br>
					<small>
						{{product.product_pitch}}
					</small>
				</h4>
				
			</div>
		</div>
		<br>
		{% empty %}
		<p><small>No Products yet</small></p>
		{% endfor %}
	</div>
</div>


{% endblock %}

{% block content_3 %}
<div class="row">
	<div class="col">

		<a href="{% url 'user:claim_list' %}" class="pull-right right-deck" role="button">Claim a product?</a>
		<br>
	</div>
</div>
{{ block.super }}
{% endblock %}